### ISSUE TITLE
How to use tmLanguage files by path?

### ISSUE THREAD

**Issue by ChrisMGeo** [octref/shiki#10]
How do I use a custom grammar, in the form of a string of it's path for the syntax highlighting in shiki?
I want to do this in the function `shiki.codeToHtml()`.

**Comment by hacknug** [comment]
This is what I hav eon my project and it works fine:

```js
const shiki  = require('shiki')

{ theme: shiki.loadTheme('./static/themes/dracula.json') }
```

**Comment by idleberg** [comment]
@hacknug Chris was asking for a way to load `.tmLanguage` syntax definitions, not themes

**Comment by hacknug** [comment]
@idleberg I see. Sorry for the confusion!

**Comment by thetutlage** [comment]
Looking for same
