### ISSUE TITLE
How to use a custom theme?

### ISSUE THREAD

**Issue by usernamehw** [octref/shiki#13]
Is this example correct?

https://github.com/octref/shiki/blob/master/packages/themes/README.md#yours

```typescript
const { Shiki } = require('shiki')
const { loadTheme } = require('shiki-themes')

const t = loadTheme('./prism.json');
const h = await new Shiki(t);
```

> Uncaught (in promise) TypeError: Shiki is not a constructor

**Comment by octref** [comment]
Sorry that was outdated API. I fixed it.
