### ISSUE TITLE
C# language support

### ISSUE THREAD

**Issue by forrestab** [octref/shiki#14]
I was looking through the `packages\languages\src\lang.ts` for `c#` or `csharp`, but couldn't find it. Can support be added or should I use a similar language like `java`? If support can be added, how would I go about that?

I noticed `.tmLanguage` files are being used, could something from this repo [dotnet/csharp-tmlanguage](https://github.com/dotnet/csharp-tmLanguage) be used?

**Comment by octref** [comment]
Nope, it's actually here upstream: https://github.com/Microsoft/vscode/blob/master/extensions/csharp/syntaxes/csharp.tmLanguage.json. I can add it.
