### ISSUE TITLE
Is it possible to use from vscode extension?

### ISSUE THREAD

**Issue by usernamehw** [octref/shiki#17]
> ENOENT: no such file or directory, open 'node_modules\onigasm\lib\onigasm.wasm'

I have no idea what `.wasm` is and how to handle it...

**Comment by octref** [comment]
Seems someone else already did it: https://github.com/Microsoft/vscode/issues/65559 and https://github.com/rubyide/vscode-ruby/issues/506. So this is definitely possible.

**Comment by usernamehw** [comment]
So, I still have no idea how. Abandoning it then.

**Comment by octref** [comment]
@usernamehw You should subscribe to https://github.com/microsoft/vscode-docs/issues/2212. I was talking to @rebornix and we'll put together a guide for using WASM in extensions.

**Comment by ZelCloud** [comment]
Issue https://github.com/microsoft/vscode-docs/issues/2212 seems to have been closed without an example being provided.

Could we get a small sample showing us how to load the shiki onig.wasm file in an vscode extension and then using it within a webview?

**Comment by muenzpraeger** [comment]
@ZelCloud Check the link in https://github.com/microsoft/vscode/issues/65559#issuecomment-751689987 for instructions.
