### ISSUE TITLE
Material Ocean is not correct one

### ISSUE THREAD

**Issue by lorvent** [octref/shiki#19]
Hello,
I don't think material ocean is exact copy of oceanic theme,

when i compare color codes, most of the are matching for deep ocean theme https://github.com/ChrisRM/material-theme-jetbrains/blob/master/src/main/resources/themes/deepocean.theme.json

**Comment by octref** [comment]
Yes, they are https://github.com/material-theme/vsc-material-theme. You can load your own theme as well.
