### ISSUE TITLE
add toml filetype?

### ISSUE THREAD

**Issue by sw-yx** [octref/shiki#20]
i'd like to add `toml`, which my company uses a lot and is recognized on github: https://github.com/toml-lang/toml

i think as a first step we could simply add it as an alias of yaml. what do you think?

**Comment by octref** [comment]
I can add it. There's a textmate bundle here: https://github.com/textmate/toml.tmbundle/blob/master/Syntaxes/TOML.tmLanguage

**Comment by sw-yx** [comment]
oo thank you!! i didnt know where to find.

**Comment by octref** [comment]
Published in 0.1.6.

**Comment by sw-yx** [comment]
thank you!

**Comment by sw-yx** [comment]
hey @octref - did the publish go thru? https://www.npmjs.com/package/shiki shows 0.1.5 still

**Comment by octref** [comment]
lerna failed to publish. Now 0.1.6 should be up.
