### ISSUE TITLE
Some VSCode themes are not proprely configured

### ISSUE THREAD

**Issue by firstclown** [octref/shiki#8]
Problem: Trying to use solarized_dark, solarized_light, or monokai_dimmed themes doesn't work.

Solution: The names of the themes does not match the name of the theme file, and so Shiki can't find the theme. Since the file names are set by VSCode, the names in the code should be changed to match the file names.

- solarized_dark → solarized-dark
- solarized_light → solarized-light
- monokai_dimmed → dimmed-monokai

**Comment by octref** [comment]
Thanks! The fix is available in 0.1.4.
